### ISSUE TITLE
[Sugestion] Pokemon To Evolve Filter.

### ISSUE THREAD

**Issue by crausk** [NecronomiconCoding/NecroBot#1008]
Like the new feature Pokemon to transfer filter but with evolutions. I would be awesome if the bot has that feature.

If i catch a dratini i dont want to evolve it if it does not has 90%+ IV

But if i catch a caterpie i want to evolve even if it has 1% IV.

**Comment by ProfessorPoke** [comment]
"EvolveAboveIvValue": 90.0,
  "EvolveAllPokemonAboveIv": true,

  "EvolveAllPokemonWithEnoughCandy": false,
  "PokemonsToEvolve": [
    "caterpie",

What you want to do is already implemented. Look at these sections in the config file. Just don't put Dratini in the PokemonsToEvolve list because you want to save Candies for a 90%+ Dratini, right? Similarly, don't put Magikarp or Evee in that list.

**Comment by crausk** [comment]
Actually I use the PokemonToEvolve List with custom pokemon. But for example I want to move the bot to a "Dratini" nest then i want to evolve every dratini with more than 90% IV. I know that i can do that putting dratini into the PokemonToEvolve List and removing every pokemon from that list and setting EvolveAboveIvValue to 90%. But if u know the new feature "Pokemon To Transfer Filter" if that feature is implemented with Evolves I will be abble (with some custom edit) to Evolve Every rare pokemon with more than 90% IV and at the same time evolve every common pokemon like weedle, ratata, pidgey every time the candy counter reach 12 setting the common pokemon IV to evolve with to 1%+ (just for XP farming)
