### ISSUE TITLE
GUYS making a million issues about the same thing doesnt help u...... Read if ur getting clipboard errors

### ISSUE THREAD

**Issue by Iluveulongtime** [NecronomiconCoding/NecroBot#1152]
If ur bot doesnt give you the code it will not let you do it manual, theres no way to find it other wise. What  was just introduced was on google's side to block this problem. 

BUTTT to get around this just make a pokemon go trainer account on the site, and use that to log into the bot instead of google accounts.

**Comment by GamberroIbz** [comment]
But are u saying that wont be a solution, better way is create a ptc account and start again?

**Comment by Gratataa** [comment]
I've read some of the posts and their comments and it looks like there is some other ways, this is most directed to those just starting to bot or making new accounts to bot. Having ur old accounts wouldn't experience this problem since its alrdy authenticated and you don't need to redo this unless u delete ur auth for some reason.

**Comment by Ilses** [comment]
This is a post, not an issue. Close, please
