### ISSUE TITLE
DisplayHighestsPerfect/CP stuck after some time

### ISSUE THREAD

**Issue by shejk0** [NecronomiconCoding/NecroBot#118]
After running bot for a while, it's stucked at showing/spamming "DisplayHighestsPerfect"& "DisplayHighestsCP". Just restarting .exe won't work, need to recompile the whole to work again.

**Comment by haxlife** [comment]
i saw it happening, after the 30m crash & auto restart. The coord file was filled with crap NaN stuff and forced this behaviour. Deleting the coord file stopped the bucle stuck of  "DisplayHighestsPerfect"& "DisplayHighestsCP" console msgs

**Comment by AdnanCukur** [comment]
#133 

This happens because the 30minute crash is not yet fixed, we just got a workaround doing a soft restart of the bot. 

When the 30minute crash occurs, the bot writes broken coordinates to the Coords.txt and when the bot restarts it tries to place you at the broken coordinates which causes it to break and restart again over and over. 

We have a broken fix that checks for the "NaN" string but that doesnt work cause NaN is parseable as a double. 

Possible fix is to check the entire coords.txt if it contains NaN string, then put defaultsettings

**Comment by ReddoKiddo** [comment]
should be fixed? if not try to check FAQ in discord, and if that doesn't help open a new one pl0x
