### ISSUE TITLE
Missing Google Login form..

### ISSUE THREAD

**Issue by ilikesomething** [NecronomiconCoding/NecroBot#1194]
When choosing AUTH google, the bot doesn't even ask for a username or password and just try to connect with ...i don't know wich info....

Then the same error as other people occurs :
![aaa](https://cloud.githubusercontent.com/assets/13218000/17211970/a22134d6-54cc-11e6-875b-c490eba4acde.png)

Same problem on older versions of the bot..

It was working fine yesterday so...

**Comment by flaxues** [comment]
This is being fixed... Maybe look in other issues before posting a new one?

**Comment by mich3lam** [comment]
I wish people could read before opening another issue. 230 issues are open, yet new ones are made. amazing how blind people are

**Comment by ilikesomething** [comment]
If you read my issue you would see that my main problem is not the one on the screenshot

**Comment by mich3lam** [comment]
@ilikesomething google is not supposed to ask you for username and pasword. it should give u a key to get a token from and THAT is the same problem as someone else. so you need to learn how to read not anyone else

**Comment by Kalashnikitty** [comment]
Please close the issue tab until u have fixed the API problems!

**Comment by ilikesomething** [comment]
@mich3lam No need to be that rude, you looks very frustrated, i'm very sorry for you.

By the way the code is copied in my clipboard even if it says the other thing on the console.

**Comment by WinSCaP** [comment]
#1107 Error Google Auth
#1121 Device Code Error
#1124 Google auth not working aymore since 10:15pm
#1141 just started using it and this happens... anyone knows how to fix it ?
#1146 【fix】no Google code or clipboard
#1150 No google code
#1152 GUYS making a million issues about the same thing doesnt help u...... Read if ur getting clipboard errors
#1154 Temporary Fix to Clipboard Problem
#1158 Is Bot dead now?? It was good while it lasted :)
#1162 When launching Compiled Release v0.1.9 - ERROR: Couldnt copy to clipboard, do it manually
#1167 How do I fix this?
#1168 Couldnt copy to clipboard
#1169 [Guide] Fix Google Device Auth Issue *Outdated, working on fix*
#1174 Google Refresh Token
#1178 Google Token Problem
#1181 Error: No Google Login Code
#1182 Error While Executing PoGo.NecroBot.CLI.exe
#1190 No code copied to clipboard (altough it said it has)
#1192 [FIX] (ERROR) Couldnt copy to clipboard, do it manually

This is not a chatbox, this is not a forum, this is not helpdesk. 

**This is a bugtracker, please behave accordingly.**

**Comment by mich3lam** [comment]
@ilikesomething because im tired of people spamming the issue here with shit when other ppl need to check all of them after that and clean the whole issue tab from spam

**Comment by ilikesomething** [comment]
@mich3lam if you didn't jump like a kid to the comment section after seeing my screenshot, you may have find out that my ticket is not about the google device bug (and as i said just after the screen, i m aware that the problem is known, but obviously you didn't read). My concern was about the soft not asking for the login, but as explained after it doesn't need it as for now. Another bot asked it and i just was confused.

Anyway i understand what this place is, i use it everyday since like 5 years or so.

**Comment by mich3lam** [comment]
@ilikesomething if u used a bot that asked u for ur account and u gave it ur account better check the source lmao. i havent seen one thats asking for ur google info.
