### ISSUE TITLE
Logging problem

### ISSUE THREAD

**Issue by Ejjjj** [NecronomiconCoding/NecroBot#1207]
Hello , i always get this problem

https://gyazo.com/7923a3b6c9b3188e4223911a636f021d

please help me ;c

**Comment by Ejjjj** [comment]
i tried to put the old one and got this error 

https://gyazo.com/71d382945d0dc9a8331057a035a4e9d6

**Comment by WinSCaP** [comment]
#1107 Error Google Auth
#1121 Device Code Error
#1124 Google auth not working aymore since 10:15pm
#1141 just started using it and this happens... anyone knows how to fix it ?
#1146 【fix】no Google code or clipboard
#1150 No google code
#1152 GUYS making a million issues about the same thing doesnt help u...... Read if ur getting clipboard errors
#1154 Temporary Fix to Clipboard Problem
#1158 Is Bot dead now?? It was good while it lasted :)
#1162 When launching Compiled Release v0.1.9 - ERROR: Couldnt copy to clipboard, do it manually
#1167 How do I fix this?
#1168 Couldnt copy to clipboard
#1169 [Guide] Fix Google Device Auth Issue *Outdated, working on fix*
#1174 Google Refresh Token
#1178 Google Token Problem
#1181 Error: No Google Login Code
#1182 Error While Executing PoGo.NecroBot.CLI.exe
#1190 No code copied to clipboard (altough it said it has)
#1192 [FIX] (ERROR) Couldnt copy to clipboard, do it manually
#1194 Missing Google Login form..
#1207 Logging problem

**Comment by Ejjjj** [comment]
it's working now thank you ^^

**Comment by ereorrman** [comment]
what??? how ???

**Comment by flvnt666** [comment]
how???

**Comment by dirtybass** [comment]
How you solve it @Ejjjj  ?

**Comment by alaswingit** [comment]
yes, how to solve it?

**Comment by Ejjjj** [comment]
Copy your token from old version

Then go to the directory for your Necrobot (v7 Bot):
PoGo.NecroBot.CLI > bin > Debug > Config

Open to the file in there with a text editor or VS

{
"AuthType": "google",
"GoogleRefreshToken": "PUT YOUR TOKEN HERE",
"PtcPassword": null,
"PtcUsername": null
}

**Comment by Ejjjj** [comment]
You need to have your old token to solve this problem

**Comment by aikoncwd** [comment]
@flvnt666 You can't, you need your old/original google-token

**Comment by ereorrman** [comment]
yep, i got no 0.17 version
all my hope is somehow author have a way to fix this prob

**Comment by aikoncwd** [comment]
@ereorrman Any dev can't solve this... You have 2 options to login on the servers:

1. Google Account
2. PTC

PTC servers are down/unstable, you can wait and try until PTC is online again.
You need to have a valid/autenticated token for your DeviceID to access Google Acount. You can't generate new tokens because Google is not accepting more queries/request (maybe a ban? I don't know). But you can still use your old/previous token (if you had one)

**Comment by aikoncwd** [comment]
btw, there is the solution! :)

https://github.com/NecronomiconCoding/NecroBot/commit/044cb985357736ce9626c407ec37d9308aaa4b99

**Comment by wigunareza** [comment]
is there a way to get new google token for new account?
