### ISSUE TITLE
google auth fixed?

### ISSUE THREAD

**Issue by PepoelpepO** [NecronomiconCoding/NecroBot#1218]

**Comment by WinSCaP** [comment]
#1107 Error Google Auth
#1121 Device Code Error
#1124 Google auth not working aymore since 10:15pm
#1141 just started using it and this happens... anyone knows how to fix it ?
#1146 【fix】no Google code or clipboard
#1150 No google code
#1152 GUYS making a million issues about the same thing doesnt help u...... Read if ur getting clipboard errors
#1154 Temporary Fix to Clipboard Problem
#1158 Is Bot dead now?? It was good while it lasted :)
#1162 When launching Compiled Release v0.1.9 - ERROR: Couldnt copy to clipboard, do it manually
#1167 How do I fix this?
#1168 Couldnt copy to clipboard
#1169 [Guide] Fix Google Device Auth Issue *Outdated, working on fix*
#1174 Google Refresh Token
#1178 Google Token Problem
#1181 Error: No Google Login Code
#1182 Error While Executing PoGo.NecroBot.CLI.exe
#1190 No code copied to clipboard (altough it said it has)
#1192 [FIX] (ERROR) Couldnt copy to clipboard, do it manually
#1194 Missing Google Login form..
#1207 Logging problem
#1218 google auth fixed?

This is not a chatbox, this is not a forum, this is not helpdesk. 

**This is a bugtracker, please behave accordingly.**

**Comment by aikoncwd** [comment]
Dev's are working on it... I saw a few commits about that issue, maybe on next update will be fixed

**Comment by PepoelpepO** [comment]
thanks!! and it knows when will be the next update? thanks

**Comment by aikoncwd** [comment]
@PepoelpepO Yes , give me a second so I can ask that to my magic cristal ball... :8ball:

**Comment by Joshuamtgprice** [comment]
I swear man, I really just do NOT get people these days, lmfao... Hell, I've been sitting here checking back off and on, just watching the commits being made. So that way, I wouldn't have to come here, and do what all these other fracking idiots are doing, which is just clogging up the issue list with a hundred thousand dupe reports, Lol..

Does anyone mind.. if like.. I just go psycho, and start :gun:-ing and :hocho:-ing the next few motha' ****er's that write up issues so needlessly, and send them to the :hospital: with their :facepunch:-ed in...

Lul..  :100::100::100:

**Comment by aikoncwd** [comment]
@Joshuamtgprice amén bro :+1:
