### ISSUE TITLE
[Request] Wait until Evolution cycle before transferring

### ISSUE THREAD

**Issue by ChainRythm** [NecronomiconCoding/NecroBot#127]
Keep all Pokemon until the box is full, or set Time limit.
Upon box full or time limit, evolve all available.
Once evolutions are complete, transfer all, according to set parameters (MinCP,MinIV,Duplicate)

Is this possible?

This can also be linked to Lucky egg use once that is implemented to get the max amount of xp.

**Comment by Owinger** [comment]
I would love to see this happen.

**Comment by minhquangpm** [comment]
Would love to see this come true

**Comment by dbfy** [comment]
By Full do you mean the Bag > 50 Pokemon?

**Comment by ChainRythm** [comment]
When i say "box is full", it means that your maximum amount of Pokemon that can be held is at its limit. Simple.

**Comment by dbfy** [comment]
OK Idk if the enum for that is valid yet, gotta check. I know for sure profile.Profile.PokeStorage returns the max amount you can hold. Might have to do a manual count.

**Comment by dbfy** [comment]
OK Um I Don't know if this will work but.

Add this async into Logic.cs anywhere

>         private async Task<int> CountNumberOfPokemons()
        {
            var pokeInv = await _inventory.GetPokemons();
            return pokeInv.Count();
        }

Then in public async Task PostLoginExecute()
Change to

>         public async Task PostLoginExecute()
        {
            while (true)
            {
                _playerProfile = await _client.GetProfile();
                await DisplayPlayerLevelInTitle();
                var pokemonCount = await CountNumberOfPokemons();
                if (pokemonCount == _playerProfile.Profile.PokeStorage)
                {
                    Logger.Write($"Pokemon Count is {pokemonCount}/{_playerProfile.Profile.PokeStorage}", LogLevel.Info);
                    if (_clientSettings.EvolveAllPokemonWithEnoughCandy) await EvolveAllPokemonWithEnoughCandy(_clientSettings.PokemonsToEvolve);
                    if (_clientSettings.TransferDuplicatePokemon) await TransferDuplicatePokemon();
                }
                
                await DisplayHighests();
                await RecycleItems();
                await ExecuteFarmingPokestopsAndPokemons();


I'm testing it now so we'll know i an hour.

**Comment by ChainRythm** [comment]
Nice! 👍 Please let me know if it works.

**Comment by dbfy** [comment]
Well it's 250 max atm, i'm only at 87. But for sure the transfers are called from somewhere else because it's still transferring pokemon. I'll keep at it.

**Comment by dbfy** [comment]
Ok Yea It works, I have a better way now too.
[https://puu.sh/qbq6O/d8bf2786dc.png](https://puu.sh/qbq6O/d8bf2786dc.png)

Gimme sec to do it.

**Comment by dbfy** [comment]
Ok yea it works. Because what I posted above eats CPU like crazy.

In Logic.cs
Declare static
`        private static int _currentPokemonCount;
`
then at the end of `CatchEncounter(EncounterResponse encounter, MapPokemon pokemon)`
add ` _currentPokemonCount++;`

so it looks like
`} while (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchMissed ||
                     caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchEscape);
            _currentPokemonCount++;`
then in `PostLoginExecute()`
add change it to
`
            while (true)
            {
                _playerProfile = await _client.GetProfile();
                await DisplayPlayerLevelInTitle();
                await DumpInfo();
                if (_currentPokemonCount == 0)
                {
                    _currentPokemonCount = await CountNumberOfPokemons();
                }
                if (_currentPokemonCount >= 85) //_playerProfile.Profile.PokeStorage) Storage is 250
                {
                    Logger.Write($"Pokemon Count is {_currentPokemonCount}/{_playerProfile.Profile.PokeStorage}", LogLevel.Info);
                    if (_clientSettings.EvolveAllPokemonWithEnoughCandy) await EvolveAllPokemonWithEnoughCandy(_clientSettings.PokemonsToEvolve);
                    if (_clientSettings.TransferDuplicatePokemon) await TransferDuplicatePokemon();
                }
                
                await DisplayHighests();
                await RecycleItems();
                await ExecuteFarmingPokestopsAndPokemons();
`
I hardcoded it for 85, maybe Necronomicon can change it.
Finally inside `TransferDuplicatePokemon(bool keepPokemonsThatCanEvolve = false)`
add this after `var transfer = await _client.TransferPokemon(duplicatePokemon.Id);`
so it looks like
`var transfer = await _client.TransferPokemon(duplicatePokemon.Id);
                _currentPokemonCount--;`

What it's going to do is, everytime you catch a pokemon, it's going to increment the initial value in PostLoginExecute() that will set on initial start(so it wont keep polling the LINQ call[expensive])
If the count is above the hard limit `85` it's going to start selling IF you set your `EvolveAllPokemonWithEnoughCandy` to true.
`_currentPokemonCount` decrements on every transfered pokemon.

Have fun.

**Comment by dbfy** [comment]
Oh you can see this working by changing `var message =` inside `DisplayPlayerLevelInTitle(bool updateOnly = false)`
to this
`var message =
                    $"{playerName} | Level {playerStat.Level}: {playerStat.Experience - playerStat.PrevLevelXp - xpDifference}/{playerStat.NextLevelXp - playerStat.PrevLevelXp - xpDifference}XP Stardust: {_playerProfile.Profile.Currency.ToArray()[1].Amount} Latt: {_client.CurrentLat} Long: {_client.CurrentLng} #{pokemonCount}/{_playerProfile.Profile.PokeStorage}";
                `

**Comment by vcafezinho** [comment]
This would be perfect, please devs, implement this =D
