### ISSUE TITLE
v0.5.0 - Keeps using Great Balls even for 100 CP PMs, I have set "useGreatBallabovecp" to 800!

### ISSUE THREAD

**Issue by ssm34** [NecronomiconCoding/NecroBot#1690]

**Comment by chimichandra** [comment]
Set these Values in the settings, happening because #1678 
"UseGreatBallAboveCp": 1000,
"UseUltraBallAboveCp": 1250,
"UseMasterBallAboveCp": 1500,
"UseGreatBallAboveIv": 85,
"UseUltraBallAboveIv": 90,
"UseGreatBallBelowCatchProbability": 0.3,
"UseUltraBallBelowCatchProbability": 0.2,
"UseMasterBallBelowCatchProbability": 0.05,

or customize the settings

**Comment by Aneduna** [comment]
Yea. As of the new versions Great balls and higher also get thrown at "weaker" Pokemons under certain conditions

**Comment by Larkspeed** [comment]
tell me about it, it just burned through all my ultra and great balls and left me with only regular balls.

160 Ultra balls down the tubes
