### ISSUE TITLE
Keep Pokemon with the Highest IV, HighestCP

### ISSUE THREAD

**Issue by panzer168** [NecronomiconCoding/NecroBot#211]
Sometimes I have 3 pokemons with IV's from 85 all the way to 95

Not sure about other people.. but I don't need one highest IV of the pokemon..

Thank you

**Comment by LasaFawkes** [comment]
Just set your KeepMinIVPercentage and KeepMinCP values higher, that should transfer everything below those thresholds when BOTH conditions are met.
For instance: let's imagine you have KeepMinCP set to 800 and your KeepMinIVPercentage set to 90. If you catch a 850 CP pokémon with 60% perfect IVs, the bot will keep it because it's over the CP threshold. Likewise, if you catch a 20 CP pokémon with 95% perfect IVs, it will keep it because it's over the IV threshold.
