### ISSUE TITLE
[Request] Bot currently prioritizes CP over IV

### ISSUE THREAD

**Issue by LasaFawkes** [NecronomiconCoding/NecroBot#241]
I've done a few tests about this and posted them on a previous issue (#97), but I just noticed it is happening again and, in this case, I don't have any other pokémon of the same type with higher IVs so it's pretty clear now.

(19:07:04) (TRANSFERED) Meowth with 225 (79,57 % perfect) CP (Best: 381 | (37,66 % perfect))
(19:11:13) (TRANSFERED) Diglett with 90 (67,77 % perfect) CP (Best: 224 | (53,20 % perfect))

Any chance we can get a "Prioritize IV over CP when transferring" toggle?

EDIT: I'm thinking it's probably because I don't have any other pokémon of the same species and they are all below the minCP and minIV threshold, and that when I get one over said thresholds, it will ditch the worse one automatically.

That makes sense, I guess, but I think the bot should keep the pokémons progressively as well, so it automatically ditches the worst pokémon when capturing a new one until it reaches the set thresholds, right? I don't even know if I'm explaining myself properly :sob:

**Comment by secw** [comment]
Yes you're right, it will ditch the lowest CP duplicates unless it has the minimum IV threshold you set (default 85).

**Comment by PocketMobsters** [comment]
I'll work on this.

**Comment by CTDragon** [comment]
I thought about this and looked at the logic. IV includes calculations for the abilities of the pokemon. If it is a pokemon that can evolve, the moves get randomized after evolve. There would need to be 2 calculations for IV, one based mostly on health/cp ratio for those that can evolve, and one based on healt/cp/abilities (the logic that is already there) if we are to change this.
A little more work than the issue seems to suggest.
OR only compare using IV for those pokemon who cannot evolve and not IV at all for the ones that can. That would be a little less work.

**Comment by PocketMobsters** [comment]
Working on creating the pull request but I have added a toggleable option to prioritize IV over CP, so, in the case of duplicates, it'll keep the highest IV pokemon.

**Comment by PocketMobsters** [comment]
Please close this issue since I added the functionality requested.

**Comment by Hitsuomy** [comment]
I was just using a CP cap extremely high, so the bot will never capture a pokemon with 10k cp, will just leave the 90% IVs without transfer. Pretty easy.

**Comment by ridoknight** [comment]
[00:17:26] Requesting TransferPokemonOut
[00:17:27] Gastly with 340 (71,56 % perfect) CP (Best: 444 | (69,15 % perfect))

it is not working -_- bot send my %97 magicarp to transfer. I limited %95 IV and send "All" magicarps to professor. some problem here i guess.
