### ISSUE TITLE
[REQUEST]: BEST setting ?

### ISSUE THREAD

**Issue by n3o999** [NecronomiconCoding/NecroBot#251]
Hi, it's possible to have a best setting for user.setting. for level up, or not evolve, etc? thanks

**Comment by AdnanCukur** [comment]
Best setting is dependant on opinion. You want the fastest bot, or the most human like bot ?. The default settings are a good mixture of both.

**Comment by gewoon** [comment]
I think the defaults are pretty good.

**Comment by Hitsuomy** [comment]
I just edit the values to itens, 200 razzberries and only 20 pokeballs are a little overboard for me.
I would recommend using most default, don't evolve, let the bot transferring duplicates, use manually a lucky egg and evolve a ton of shit later, much more exp, the bot doesn't use it automatically for now, so it's probably the best option.
I also changed the speed, 50km/h is a bit higher for my location, I let ins 14 km/h since I'm spoofing on a park. It's easy to edit, just open the project and edit. Everything is in english and easy to understand.

**Comment by gewoon** [comment]
How would you add a Lucky egg manually if you're not farming in a city close to you?
