### ISSUE TITLE
Visual studio question

### ISSUE THREAD

**Issue by truxy** [NecronomiconCoding/NecroBot#306]
Hello, is it possible 2 close the studio after the bot is running?.
i tryed 2 close it by pressing the X but then it asked me if i wanted 2 stop the debugging and if i press Yes then the bot closes aswell 

thanks.

**Comment by seanbailey28** [comment]
Go to the Debug menu and click "detatch all". You'll be able to shut VS and keep it running then.

**Comment by Pakobbix** [comment]
Instead of starting the debugging, Right Click on PockemonGo.RocketAPI.Console and click on "Rebuild" if it's done, close Visual Studio. 
Open the Bot-master folder, PockemonGo.RocketAPI.Console Folder, Bin Folder and Debug (or Release folder, depends on your settings) and just open the PokemonGo.RocketAPI.Console.exe.

**Comment by truxy** [comment]
Thanks for all those answers

**Comment by Shroomzie** [comment]
remember to close the issue if you find a solution
