### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Maximu5** [NecronomiconCoding/NecroBot#307]
Y doesn't the bot transfer Pinsir? i have so many of them-.-

**Comment by Hitsuomy** [comment]
You are probably botting at Central Park right? Bot keeps duplicates of pokemons with high IVS, 85%+, there is a TON of Pinsirs at Central Park, I went from 0 to 680 berries in one day, capturing 200-300 Pinsirs in one day, you can count that at least 5% of them will have 85%+ IVs, that's why so many duplicates.
