### ISSUE TITLE
Map Bot Integration

### ISSUE THREAD

**Issue by benda95280** [NecronomiconCoding/NecroBot#385]
It's possible to integrate a map to track the Bot, see where is him ?

http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563636-botmap-v1-0-realtime-map-pokemon-bots.html

Thanks ;)

**Comment by TheCrimsonDevil** [comment]
Maybe I'm confused, but doesn't it already do this?

**Comment by l3uddz** [comment]
that project works fine if you place the botmap folder inside Config folder, and open sinatra.rb and replace the coords.txt with Coords.ini

**Comment by Tropicocity** [comment]
I can't open Sinatra.rb for the life of me. I've opened a command prompt window with ruby, but I can't navigate to my necro bot folder. Am I missing something with the ruby install? I used the rubyinstaller program. Thanks

**Comment by Tropicocity** [comment]
I'm having the hardest time ever getting sinatra to run. I'm in a ruby command prompt window and I've navigated to where the sinatra.rb is within my pokemongo.rocketapi.console>bin>debug folder, but i get the following error: 

C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from sinatra.rb:1:in `<main>'

Any ideas?

**Comment by l3uddz** [comment]
When you install ruby, make sure you select the Add to PATH option make sure its selected).
Extract that botmap folder to your Config folder (inside NecroBot\PokemonGo.RocketAPI.Console\bin\Debug\Configs). Right click on the sinatra.rb and open with notepad, replace coords.txt with Coords.ini (for both entrys). 
Once this is done, hold Shift key and right click inside the botmap folder and click Open command prompt here, then simply enter "ruby sinatra.rb".
Open your browser http://localhost:3000 and you should see a map, that begins plotting where it is similar to the image i posted above (assuming your bot is running).

**Comment by l3uddz** [comment]
Did you do follow the instructions on his github and do "gem install sinatra"? because if you have then am not sure really, everything worked first time for me after doing like i said above and following the github instructions.

**Comment by Tropicocity** [comment]
I've just read your replies. First off, thankyou so much for the help and the quick responses :)!

Right, so I re-ran the installer and made sure the PATH part was ticked. I think the issue might be I don't actually HAVE a bin\Debugs\Configs folder - the Debugs folder is currently empty. 

Is that because I've literally just done a fresh SVN checkout of the latest update of the bot? (I literally deleted my previous bot folder and created a new one for it). Thanks in advance!

**Comment by l3uddz** [comment]
I believe the Configs folder may be created on first run so perhaps set your bot up and get it running, then follow the instructions above provided Configs folder is created, even if it is not, simply replace the folder i said above so that the botmap folder is in the same location as the Coords.ini file which for me is inside the Configs folder.

**Comment by Tropicocity** [comment]
It turns out I've not had nearly enough sleep! All this time I was looking at your comment about doing a gem install of sinatra, I had no idea it literally meant to type 'gem install sinatra' the same way you'd type python <something> or ruby <something>.  I'm very new to all of this, my only programming experience is making a game in visual basic as part of a college project :) I think I was reading it and mistaking sinatra for ruby haha. I've managed to get it running but gotten the error going to localhost:3000, but I'm 99% sure that's just because I don't have my bot running yet!
Time to use a pokemon map to find a nice location to start botting, and hopefully this thing should follow it :D

**Comment by l3uddz** [comment]
haha no problem =). have fun

**Comment by Tropicocity** [comment]
Hi again, sorry to keep pestering you. It turns out I keep getting the error even With the bot running :( here's a screenshot of what I'm seeing when I run sinatra.rb and navigate to localhost:3000
http://prntscr.com/bwv6qw

Thanks ><

**Comment by l3uddz** [comment]
verify that Coords.ini is infact there, if it is, edit your sinatra.rb and change coords.ini to Coords.ini, it may be case sensitive, if it still isnt working, then am a little stumped...

**Comment by Tropicocity** [comment]
I have it working now, it turns out I already had a sinatra.rb running in the background and refreshing localhost:3000 was just using that one :) I needed to change my ".../coords.ini" to the full path but now it works! :D Many thanks again dude :)

**Comment by l3uddz** [comment]
no problem, glad you got it going =)
