### ISSUE TITLE
[Feature Request] Add Pokemon Slots Used/Total to Evolve and Transfer lines

### ISSUE THREAD

**Issue by Talamar1** [NecronomiconCoding/NecroBot#754]
Would be nice to see how well the system is managing Pokemon inventory capacity.  I just ran into an issue where I ran out of slots after I left it running for a while, had I known it was that close before I left I could have either manually cleared it out or adjusted my transfer settings.

**Comment by Shroomzie** [comment]
If you are using this
`"KeepPokemonsThatCanEvolve": true,`

Then i believe you should prolly use this

`"EvolveAllPokemonWithEnoughCandy": true,`

Otherwise you get what you just experienced. Honestly though, someone might think this is a good idea and implement it. but you are one in like 40 QOL issues posted atm. when QOL really isn't a priority is it?

**Comment by Talamar1** [comment]
Nope, just "like to have features, not a bug"

**Comment by Shroomzie** [comment]
Re label the heading then mate to something like [Feature Request]
