### ISSUE TITLE
[Feature Request] More Randomization Options

### ISSUE THREAD

**Issue by Sasstraliss** [NecronomiconCoding/NecroBot#808]
I propose a feature such that the bot starts not at the default coords, but somewhere within X metres of the default coords. X being configurable.

**Comment by basdxz** [comment]
Speaking of randomization, last I checked a lot of the timings are also set in stone. Would be great to also make the rest of stuff that doesn't need to be precise random to avoid future detection.

**Comment by Sasstraliss** [comment]
Perhaps also a few options for the 'UserAgent' so to speak, that it uses (and pretends to be a particular Android). Having a few that are randomly chosen and stuck to per account might help with future detection also.

**Comment by ShawnHardwick** [comment]
Edited title to be more generic as there are multiple ideas in this request. The general idea being that the bot be more random.

**Comment by Maximum-throwaway** [comment]
That is a problem with implementing randomization to functions of the bot. And yeah. "making it an option" doesn't really solve that because users are very bad at isolating switches before making issue reports.

I would like more randomization, but I'm wondering if this is really the best time for it. I remember reading in a previous report that device spoofing would be the ideal solution here. Is that even possible? I haven't checked pogoapi in awhile, have they exposed functions for setting device properties?
