### ISSUE TITLE
Does not transfer any pokemon

### ISSUE THREAD

**Issue by Lycanthe** [NecronomiconCoding/NecroBot#974]
Below is my config code. "TransferDuplicatePokemon": set true. But it doesn't transfer. Though cleans the inventory from potions etc. Maybe someone could see a mistake? Thanks a lot!

"AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "C:\\Users\\1\\Desktop\\Release\\Release\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 40.626425,
  "DefaultLongitude": -74.036989,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",

"KeepMinCp": 1000,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 95.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 1000,
  "PokemonsNotToTransfer": [

 "PrioritizeIvOverCp": false,
  "ProfilePath": "C:\\Users\\1\\Desktop\\Release\\Release",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": false,
  "WalkingSpeedInKilometerPerHour": 300.0,
  "WebSocketPort": 14251
}

**Comment by diegomfdez3** [comment]
+1 here.

**Comment by Unentertained** [comment]
Seems like you deleted a closing bracket while editing your PokemonsNotToTransfer list.


"AmountOfPokemonToDisplayOnStart": 10,
"AutoUpdate": true,
"ConfigPath": "C:\Users\1\Desktop\Release\Release\config",
"DefaultAltitude": 10.0,
"DefaultLatitude": 40.626425,
"DefaultLongitude": -74.036989,
"DelayBetweenPokemonCatch": 2000,
"EvolveAboveIvValue": 95.0,
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": false,
"GpxFile": "GPXPath.GPX",

"KeepMinCp": 1000,
"KeepMinDuplicatePokemon": 1,
"KeepMinIvPercentage": 95.0,
"KeepPokemonsThatCanEvolve": false,
"MaxTravelDistanceInMeters": 1000,
"PokemonsNotToTransfer": [
**],**
"PrioritizeIvOverCp": false,
"ProfilePath": "C:\Users\1\Desktop\Release\Release",
"RenameAboveIv": false,
"TransferDuplicatePokemon": true,
"TranslationLanguageCode": "en",
"UseEggIncubators": true,
"UseGpxPathing": false,
"UseLuckyEggsMinPokemonAmount": 30,
"UseLuckyEggsWhileEvolving": false,
"UsePokemonToNotCatchFilter": false,
"WalkingSpeedInKilometerPerHour": 300.0,
"WebSocketPort": 14251
}

**Comment by Lycanthe** [comment]
Hmm, didn't copy that ] last time. It's actually like below:
"PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "nidoqueen",
    "nidoking",
    "clefable",
    "vileplume",
    "golduck",
    "arcanine",
    "poliwrath",
    "machamp",
    "victreebel",
    "golem",
    "slowbro",
    "farfetchd",
    "muk",
    "exeggutor",
    "lickitung",
    "chansey",
    "kangaskhan",
    "mrMime",
    "gyarados",
    "lapras",
    "ditto",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

**Comment by ivicanikolic034** [comment]
wow i have the same problem... with almost everything on default

**Comment by sahil16** [comment]
Since its 
"KeepMinCp": 1000 
"PrioritizeIvOverCp": false,

it would potentially mean all the Pokemon are above mincp 

if i would be you i would increase it to 2500cp and do true for ivovercp.

thats how i have solved my issue last night since they were all above mincp.

report back thanks.

 my dump

"AmountOfPokemonToDisplayOnStart": 10,
  "AutoUpdate": true,
  "ConfigPath": "D:\\Games\\pokemon biot\\v18\\config",
  "DefaultAltitude": 10.0,
  "DefaultLatitude": 34.0093515,
  "DefaultLongitude": -118.49746820000001,
  "DelayBetweenPokemonCatch": 2000,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "GpxFile": "GPXPath.GPX",
 
KeepMinCp": 2500,
  "KeepMinDuplicatePokemon": 1,
  "KeepMinIvPercentage": 100.0,
  "KeepPokemonsThatCanEvolve": false,
  "MaxTravelDistanceInMeters": 8100,

PrioritizeIvOverCp": true,
  "ProfilePath": "D:\\Games\\pokemon biot\\v18",
  "RenameAboveIv": false,
  "TransferDuplicatePokemon": true,
  "TranslationLanguageCode": "en",
  "UseEggIncubators": true,
  "UseGpxPathing": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UsePokemonToNotCatchFilter": true,
  "WalkingSpeedInKilometerPerHour": 50.0,
  "WebSocketPort": 14251

**Comment by Lycanthe** [comment]
Set like yours. Doesn't work for me. But thanks for trying!

**Comment by ivicanikolic034** [comment]
i did it and i dont know how....
i think some of these solved it:


 "KeepMinDuplicatePokemon": 4,

"PokemonsNotToTransfer": [],
  "PokemonsToEvolve": [],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": null,

**Comment by Lycanthe** [comment]
@ivicanikolic034 I'm afraid it didn't help, but thanks.

**Comment by ivicanikolic034** [comment]
at start, it transfered 40-50 pokemons... then 1 by 1 while catching new pokemons... then got stuck again :/

**Comment by ivicanikolic034** [comment]
changed

"KeepMinCp": 700,

now it started transferring again
